; ============================================================================
; NutShellGPU: GPU Hardware Emulator for Education & GPU Simulator for Education
; Version 1.10
; Author: Di Zhao (zhaodi@ucas.ac.cn), Trae CN
; Improved by: Tonghui Ming
; References: Tor M. Aamodt, Wilson W. Lun Fung, Timothy G. Rogers, General-Purpose Graphics Processor Architecture, Morgan & Claypool, 2018
; September 2026
; ============================================================================

; 1.1 机制敏感性验证配置, 延时均为模拟值
[gpgpu]
gpgpu_n_clusters = 1
gpgpu_n_cores_per_cluster = 1

[timing_v11]
core_clock_ghz = 1.5
integer_latency = 3
imul_latency = 6
writeback_ports = 2
execution_slots = 4
lsu_slots = 8

[sm_pipeline]
sp_latency = 9
sfu_latency = 13
dp_latency = 14
rf_logical_banks = 2

[sm_mem]
l1d_mshr_entries = 2

[latency_ns]
smem_hit = 4
l1_hit = 12
l2_hit = 40
dram_row_hit = 70
